In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU")

GPU is available!
Using GPU: Tesla T4


### Creating a Tensor

In [3]:
# using empty
a = torch.empty(2,3)

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.7064, 0.1629, 0.8902],
        [0.5163, 0.0359, 0.6476]])

In [8]:
# use of seed --> gor getting same value from rand function for different notebook
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# other ways

# arange
print("using arange ->",torch.arange(1,10,2)) # -> give value b/w range with step parameter

# using linspace
print("using linspace ->",torch.linspace(2,10,10)) # -> give  n  value b/w range with equal distance

# using eye
print("using eye ->", torch.eye(5)) # -> give indetity matrix

# using full
print("using full ->",torch.full((3,3),5))  # -> give constance nXm matrix of perticular number

using arange -> tensor([1, 3, 5, 7, 9])
using linspace -> tensor([ 2.0000,  2.8889,  3.7778,  4.6667,  5.5556,  6.4444,  7.3333,  8.2222,
         9.1111, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [12]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
x.shape

torch.Size([3, 3])

In [14]:
# we need to create new tensor shape like x

y = torch.empty_like(x)
y

tensor([[137538505399696,       546639024,       546637824],
        [      546919696,               0,       506280384],
        [              0,               0,               0]])

In [15]:
y.shape

torch.Size([3, 3])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [18]:
# torch.rand_like(x) # -> becouse our x has integer value but rand function generate float value

In [19]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183]])

# Tensor Data Types

In [20]:
# find data type
x.dtype

torch.int64

In [21]:
# assign data type
torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]], dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [22]:
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [23]:
# Using to()
print(x.dtype)

x.to(torch.float32)

torch.int64


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

# Mathematical Operations

1. Scalar operation

In [24]:
x = torch.rand(2,2)
x

tensor([[0.9014, 0.9969],
        [0.7565, 0.2239]])

In [25]:
# addition
print(x + 2)

# substraction
print(x -1)

# multiplication
print(x * 3)

# division
print(x / 3)

# int division
print((x * 100) // 2)

# mod
print(((x * 100) // 2) % 10)

# power
print(x**2)

tensor([[2.9014, 2.9969],
        [2.7565, 2.2239]])
tensor([[-0.0986, -0.0031],
        [-0.2435, -0.7761]])
tensor([[2.7042, 2.9907],
        [2.2695, 0.6717]])
tensor([[0.3005, 0.3323],
        [0.2522, 0.0746]])
tensor([[45., 49.],
        [37., 11.]])
tensor([[5., 9.],
        [7., 1.]])
tensor([[0.8125, 0.9938],
        [0.5723, 0.0501]])


2. Element wise operation

In [26]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.3023, 0.1784, 0.8238],
        [0.5557, 0.9770, 0.4440]])
tensor([[0.9478, 0.7445, 0.4892],
        [0.2426, 0.7003, 0.5277]])


In [27]:
# add
a + b
# sub
b - a
# multiply
a * b
# division
a / b
# power
a ** b

tensor([[0.3218, 0.2771, 0.9096],
        [0.8672, 0.9839, 0.6515]])

In [28]:
c = torch.tensor([1,2,-4,-10])
c

tensor([  1,   2,  -4, -10])

In [29]:
# abs
torch.abs(c)

tensor([ 1,  2,  4, 10])

In [30]:
# negative
torch.neg(c)

tensor([-1, -2,  4, 10])

In [31]:
d = torch.tensor([1.23,1.9,2.3,3.7,4.4])
d

tensor([1.2300, 1.9000, 2.3000, 3.7000, 4.4000])

In [32]:
# round
torch.round(d)

tensor([1., 2., 2., 4., 4.])

In [33]:
# ceil
torch.ceil(d)

tensor([2., 2., 3., 4., 5.])

In [34]:
# floor
torch.floor(d)

tensor([1., 1., 2., 3., 4.])

In [35]:
# clamp
torch.clamp(d,min=2,max=3) # -> i < 2 => 2 and i > 3 => 3 and 2 < i < 3 => i

tensor([2.0000, 2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction operation

In [36]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[0., 0., 9.],
        [5., 7., 3.]])

In [37]:
# sum
print(torch.sum(e))

# sum along columns
print(torch.sum(e,dim=0))

# sum along rows
print(torch.sum(e,dim=1))

tensor(24.)
tensor([ 5.,  7., 12.])
tensor([ 9., 15.])


In [38]:
# mean
print(torch.mean(e))

# mean along columns
print(torch.mean(e,dim=0))

# mean along rows
print(torch.mean(e,dim=1))

tensor(4.)
tensor([2.5000, 3.5000, 6.0000])
tensor([3., 5.])


In [39]:
# max and min
print(torch.min(e))
print(torch.max(e))

tensor(0.)
tensor(9.)


In [40]:
# product
torch.prod(e)

tensor(0.)

In [41]:
# stamdard deviation
torch.std(e)

tensor(3.6878)

In [42]:
# variance
torch.var(e)

tensor(13.6000)

In [43]:
# argmax
print(torch.argmax(e))

# argmin
print(torch.argmin(e))

tensor(2)
tensor(0)


4. Matrix operation

In [44]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)

print(f)
print(g)

tensor([[9, 4, 0],
        [5, 7, 5]])
tensor([[9, 9],
        [7, 5],
        [9, 8]])


In [45]:
# Matrix multiplication
torch.matmul(f,g)

tensor([[109, 101],
        [139, 120]])

In [46]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(11)

In [47]:
f

tensor([[9, 4, 0],
        [5, 7, 5]])

In [48]:
# transpose
torch.transpose(f,0,1) # -> columns(0) -> rows(1)

tensor([[9, 5],
        [4, 7],
        [0, 5]])

In [49]:
h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[9., 7., 9.],
        [2., 6., 7.],
        [7., 8., 3.]])

In [50]:
# determinent
torch.det(h)

tensor(-275.)

In [51]:
# inverse
torch.inverse(h)

tensor([[ 0.1382, -0.1855,  0.0182],
        [-0.1564,  0.1309,  0.1636],
        [ 0.0945,  0.0836, -0.1455]])

5. Comaparison Operation

In [52]:
i = torch.tensor([[5,0,1],[1,1,3]])
j = torch.tensor([[2,6,3],[1,5,9]])

print(i)
print(j)

tensor([[5, 0, 1],
        [1, 1, 3]])
tensor([[2, 6, 3],
        [1, 5, 9]])


In [53]:
# greater than
i > j

tensor([[ True, False, False],
        [False, False, False]])

In [54]:
# less than
i < j

tensor([[False,  True,  True],
        [False,  True,  True]])

In [55]:
# equal to
i == j

tensor([[False, False, False],
        [ True, False, False]])

In [56]:
# not equal to
i != j

tensor([[ True,  True,  True],
        [False,  True,  True]])

In [57]:
# greater than equal to
i >= j

tensor([[ True, False, False],
        [ True, False, False]])

In [58]:
# less then equal to
i <= j

tensor([[False,  True,  True],
        [ True,  True,  True]])

6. Special function



In [59]:
k = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[6., 1., 5.],
        [5., 0., 4.]])

In [60]:
# log
torch.log(k)

tensor([[1.7918, 0.0000, 1.6094],
        [1.6094,   -inf, 1.3863]])

In [61]:
# exp
torch.exp(k)

tensor([[403.4288,   2.7183, 148.4132],
        [148.4132,   1.0000,  54.5981]])

In [62]:
#sqrt
torch.sqrt(k)

tensor([[2.4495, 1.0000, 2.2361],
        [2.2361, 0.0000, 2.0000]])

In [63]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9975, 0.7311, 0.9933],
        [0.9933, 0.5000, 0.9820]])

In [64]:
# softmax
torch.softmax(k,dim=0)

tensor([[0.7311, 0.7311, 0.7311],
        [0.2689, 0.2689, 0.2689]])

In [65]:
# relu
torch.relu(k)

tensor([[6., 1., 5.],
        [5., 0., 4.]])

# Inplace Operation

In [66]:
m = torch.rand(3,3)
n = torch.rand(3,3)

print(m)
print(n)

tensor([[0.9178, 0.7590, 0.7775],
        [0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])
tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868],
        [0.4920, 0.0748, 0.9605]])


In [67]:
m + n

tensor([[1.5752, 1.1042, 0.8229],
        [1.5976, 0.8927, 0.9038],
        [1.4374, 0.7864, 1.0762]])

m + n which give new tensor and also occupy memory
so, for inplace addition operation use **.add_()** function

In [68]:
m.add_(n)

tensor([[1.5752, 1.1042, 0.8229],
        [1.5976, 0.8927, 0.9038],
        [1.4374, 0.7864, 1.0762]])

In [69]:
m

tensor([[1.5752, 1.1042, 0.8229],
        [1.5976, 0.8927, 0.9038],
        [1.4374, 0.7864, 1.0762]])

In [70]:
n

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868],
        [0.4920, 0.0748, 0.9605]])

In [71]:
torch.relu(m)

tensor([[1.5752, 1.1042, 0.8229],
        [1.5976, 0.8927, 0.9038],
        [1.4374, 0.7864, 1.0762]])

In [72]:
m.relu_()

tensor([[1.5752, 1.1042, 0.8229],
        [1.5976, 0.8927, 0.9038],
        [1.4374, 0.7864, 1.0762]])

# Copying a Tensor

In [73]:
a = torch.randint(size=(3,3),low=0,high=10)
a

tensor([[2, 9, 5],
        [0, 4, 2],
        [7, 1, 1]])

In [74]:
b = a
b

tensor([[2, 9, 5],
        [0, 4, 2],
        [7, 1, 1]])

In [75]:
a[0][0] = 0
a

tensor([[0, 9, 5],
        [0, 4, 2],
        [7, 1, 1]])

In [76]:
b

tensor([[0, 9, 5],
        [0, 4, 2],
        [7, 1, 1]])

if we change any value in a also its change in b

In [77]:
print(id(a))
print(id(b))

137538288526400
137538288526400


to solve this use clone() method

In [78]:
b = a.clone()

In [79]:
a[0][0] = 10

In [80]:
a

tensor([[10,  9,  5],
        [ 0,  4,  2],
        [ 7,  1,  1]])

In [81]:
b

tensor([[0, 9, 5],
        [0, 4, 2],
        [7, 1, 1]])

In [82]:
id(a)


137538288526400

In [83]:
id(b)

137538288525280

# Tensor Operation on GPU

In [85]:
torch.cuda.is_available()

True

In [84]:
device = torch.device('cuda')

In [ ]:
# creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
a

tensor([[10,  9,  5],
        [ 0,  4,  2],
        [ 7,  1,  1]])

In [ ]:
# moving an existing tensor to GPU
b = a.to(device)

In [ ]:
b + 5

tensor([[15, 14, 10],
        [ 5,  9,  7],
        [12,  6,  6]], device='cuda:0')

In [ ]:
import time
# Define the size of the matrices
size = 10000

# create random matrices on cpu

cpu1 = torch.randn(size , size)
cpu2 = torch.randn(size,size)

# measure time on cpu
start_time = time.time()
result_cpu = torch.matmul(cpu1,cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# move matrices to GPU
gpu1 = cpu1.to('cuda')
gpu2 = cpu2.to('cuda')

# measure time on cpu
start_time = time.time()
result_gpu = torch.matmul(gpu1,gpu2)
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")


Time on CPU: 15.8388 seconds
Time on GPU: 0.1221 seconds


In [ ]:
# Compare results
print("Speedup (cpu time / gpu time):", cpu_time // gpu_time)

Speedup (cpu time / gpu time): 129.0


# Reshaping Tensors

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2) # product of dimension should equal 

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.2693, 0.8009, 0.5839, 0.0061],
         [0.4671, 0.8243, 0.2861, 0.7459],
         [0.8487, 0.4059, 0.2883, 0.2220]],

        [[0.6423, 0.7098, 0.5644, 0.4549],
         [0.0729, 0.8535, 0.9793, 0.0611],
         [0.1162, 0.7666, 0.8801, 0.4203]]])

In [ ]:
# permute
b.permute(2,1,0).shape  # 2(0)-> 2 , 3(1) -> 1, 4(2) -> 0

torch.Size([4, 3, 2])

In [ ]:
b.permute(2,1,0)

tensor([[[0.2693, 0.6423],
         [0.4671, 0.0729],
         [0.8487, 0.1162]],

        [[0.8009, 0.7098],
         [0.8243, 0.8535],
         [0.4059, 0.7666]],

        [[0.5839, 0.5644],
         [0.2861, 0.9793],
         [0.2883, 0.8801]],

        [[0.0061, 0.4549],
         [0.7459, 0.0611],
         [0.2220, 0.4203]]])

### Common Uses of `unsqueeze()`

* **Adding Batch Dimensions:** Neural networks typically expect data in batches (e.g., `[batch_size, channels, height, width]`). Passing a single image with shape `[3, 64, 64]` requires `unsqueeze(0)` to become `[1, 3, 64, 64]`.
* **Broadcasting Compatibility:** Adjusting a 1D tensor to a 2D column or row vector allows correct matrix multiplication or element-wise math with other multi-dimensional tensors.
* **Channel Alignment:** Inserting color or feature dimensions at specific axes to satisfy layer requirements.

In [ ]:
# unsqueeze
c = torch.rand(226,226,3)  # (226,226,3) is image matrix
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

### Common Uses of `squeeze()`

* **Removing Batch Dimensions:** After running a single item through a model, the output often retains a batch size of one (e.g., `[1, 10]`). Using `squeeze(0)` drops that extra axis to return a clean 1D array of predictions (`[10]`).
* **Preparing for Loss Functions:** Many loss functions and evaluation metrics expect a 1D target vector of labels (shape `[N]`). If your data loader outputs labels with an extra dimension (shape `[N, 1]`), `squeeze(1)` fixes it.
* **Saving/Plotting Images:** Image libraries like `matplotlib` cannot plot grayscale images if they have an explicit channel dimension of one (shape `[28, 28, 1]`). Calling `squeeze()` reduces it to `[28, 28]` for rendering.


In [ ]:
# squeeze
d = torch.rand(1,10)
d.squeeze(0).shape

torch.Size([10])

# NumPy and PyTorch

In [ ]:
import numpy as np

tensor to numpy

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()

In [ ]:
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

numpy to tensor

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
d = torch.from_numpy(c)

In [ ]:
d

tensor([1, 2, 3])